name: Quality

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    - cron: "20 14 * * 1"

jobs:
  ### CONFIGURATION ###################################################
  #
  ### PACKAGE MANAGER
  #
  #   Set the package manager to use: "auto", "npm" or "pnpm
  #   This will configure the appropriate setup and commands throughout
  #   the workflow.
  #
  #   If set to "auto", this workflow will attempt to read the "packageManager"
  #   value of the package.json. So, make sure you have one and that you have
  #   also set this value. If it discovers pnpm, it will use that and falls
  #   back to npm if missing.
  #
  #   Example:
  #             PACKAGE_MANAGER="auto"
  #             PACKAGE_MANAGER="pnpm"
  #             PACKAGE_MANAGER="npm"
  #
  ### LINTING #########################################################
  #
  #   If we need to perform linting, set the value to "yes". Any other
  #   value will skip linting.
  #
  #   Example:  PERFORM_LINTING="yes"
  #             PERFORM_LINTING="no"
  #
  ### TESTING #########################################################
  #
  #   If we need to perform testing, set the value to "yes". Any other
  #   value will skip testing.
  #
  #   Example:  PERFORM_TESTING="yes"
  #             PERFORM_TESTING="no"
  #
  #####################################################################

  ConfigureWorkflow:
    runs-on: ubuntu-latest
    permissions: {}
    outputs:
      perform_linting: ${{ steps.cfg_main.outputs.perform_linting }}
      perform_testing: ${{ steps.cfg_main.outputs.perform_testing }}
      package_manager: ${{ steps.cfg_pm.outputs.package_manager }}
      pm_install_cmd: ${{ steps.cfg_pm.outputs.pm_install_cmd }}
      pm_default: ${{ steps.cfg_main.outputs.pm_default }}
      pm_version: ${{ steps.cfg_pm.outputs.pm_version }}
      node_version: ${{ steps.cfg_node.outputs.node_version }}

    steps:
      - name: Configure Linting and Testing
        id: cfg_main
        run: |+
          #############################################################
          PACKAGE_MANAGER="auto"
          PERFORM_LINTING="yes"
          PERFORM_TESTING="no"
          #############################################################

          echo "perform_linting=${PERFORM_LINTING}" >> "$GITHUB_OUTPUT"
          echo "perform_testing=${PERFORM_TESTING}" >> "$GITHUB_OUTPUT"
          echo "package_manager=${PACKAGE_MANAGER}" >> "$GITHUB_OUTPUT"
          echo "pm_default=npm" >> "$GITHUB_OUTPUT"

      - name: Check out repository
        uses: actions/checkout@v6

      - name: Configure Package Manager
        id: cfg_pm
        run: |+
          set -euo pipefail

          PM_DEFAULT="${{ steps.cfg_main.outputs.pm_default }}"
          PACKAGE_MANAGER="${{ steps.cfg_main.outputs.package_manager }}"
          PM_VERSION=""

          if [[ "$PACKAGE_MANAGER" = "auto" ]]; then
            printf "Package manager set to 'auto'.\n"
            printf "Detecting: "

            PM=$(jq -r .packageManager package.json)
            printf "PM=%s\n" "$PM"

            if [[ ! "$PM" ]]; then
              PACKAGE_MANAGER="$PM_DEFAULT"
            elif [[ "$PM" =~ ^(pnpm)@([[:digit:]]+.[[:digit:]]+.[[:digit:]]+)$ ]]; then
              PACKAGE_MANAGER="${BASH_REMATCH[1]}"
              PM_VERSION="${BASH_REMATCH[2]}"
            else
              PACKAGE_MANAGER="$PM_DEFAULT"
              PM_VERSION=""
            fi
          fi

          echo "package_manager=${PACKAGE_MANAGER}" >> "$GITHUB_OUTPUT"
          echo "pm_version=${PM_VERSION}" >> "$GITHUB_OUTPUT"

          if [[ "$PACKAGE_MANAGER" = "pnpm" ]]; then
            echo "pm_install_cmd=pnpm install --frozen-lockfile" >> "$GITHUB_OUTPUT"
          else
            echo "pm_install_cmd=npm ci" >> "$GITHUB_OUTPUT"
          fi

      - name: Configure Node Version
        id: cfg_node
        run: |+
          set -euo pipefail

          NODE_VERSION=""

          if ! NODE_RAW=$(jq -er '.engines.node' package.json); then
            echo "::error::engines.node is required in package.json."
            exit 1
          fi

          if [[ "$NODE_RAW" =~ [^0-9]*([0-9]+) ]]; then
            NODE_VERSION="${BASH_REMATCH[1]}"
          else
            echo "::error::Unable to parse engines.node ('${NODE_RAW}') for a Node.js version."
            exit 1
          fi

          echo "node_version=${NODE_VERSION}" >> "$GITHUB_OUTPUT"

      - name: Display Configuration
        run: |+
          printf "Linting: %s\n" "${{ steps.cfg_main.outputs.perform_linting }}"
          printf "Testing: %s\n" "${{ steps.cfg_main.outputs.perform_testing }}"
          printf "Package Manager: %s" "${{ steps.cfg_pm.outputs.package_manager }}"

          if [[ "${{ steps.cfg_pm.outputs.package_manager }}" = "pnpm" ]]; then
            printf " (%s)\n" "${{ steps.cfg_pm.outputs.pm_version }}"
          else
            printf "\n"
          fi

          printf "Package Manager Install: %s\n" "${{ steps.cfg_pm.outputs.pm_install_cmd }}"
          printf "Node: %s\n" "${{ steps.cfg_node.outputs.node_version }}"

  Lint:
    needs: ConfigureWorkflow
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Check out repository
        if: ${{ needs.ConfigureWorkflow.outputs.perform_linting == 'yes' }}
        uses: actions/checkout@v6

      - name: Install pnpm
        if: ${{ needs.ConfigureWorkflow.outputs.perform_linting == 'yes' && needs.ConfigureWorkflow.outputs.package_manager == 'pnpm' }}
        uses: pnpm/action-setup@v4
        with:
          version: ${{ needs.ConfigureWorkflow.outputs.pm_version }}

      - name: Using Node v${{ needs.ConfigureWorkflow.outputs.node_version }}
        if: ${{ needs.ConfigureWorkflow.outputs.perform_linting == 'yes' }}
        uses: actions/setup-node@v6
        with:
          node-version: ${{ needs.ConfigureWorkflow.outputs.node_version }}
          cache: ${{ needs.ConfigureWorkflow.outputs.package_manager }}

      - name: Install dependencies
        if: ${{ needs.ConfigureWorkflow.outputs.perform_linting == 'yes' }}
        run: ${{ needs.ConfigureWorkflow.outputs.pm_install_cmd }}

      - name: Perform lint check
        if: ${{ needs.ConfigureWorkflow.outputs.perform_linting == 'yes' }}
        run: ${{ needs.ConfigureWorkflow.outputs.package_manager }} run lint

  Test:
    needs: ConfigureWorkflow
    runs-on: ubuntu-latest

    permissions:
      contents: read

    strategy:
      matrix:
        node-version:
          - 22.x
          - 23.x
          - 24.x
          - 25.x

    steps:
      - name: Check out repository
        if: ${{ needs.ConfigureWorkflow.outputs.perform_testing == 'yes' }}
        uses: actions/checkout@v6

      - name: Install pnpm
        if: ${{ needs.ConfigureWorkflow.outputs.perform_testing == 'yes' && needs.ConfigureWorkflow.outputs.package_manager == 'pnpm' }}
        uses: pnpm/action-setup@v4
        with:
          version: ${{ needs.ConfigureWorkflow.outputs.pm_version }}

      - name: Using Node v${{ matrix.node-version }}
        if: ${{ needs.ConfigureWorkflow.outputs.perform_testing == 'yes' }}
        uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node-version }}
          cache: ${{ needs.ConfigureWorkflow.outputs.package_manager }}

      - name: Install dependencies
        if: ${{ needs.ConfigureWorkflow.outputs.perform_testing == 'yes' }}
        run: ${{ needs.ConfigureWorkflow.outputs.pm_install_cmd }}

      - name: Definitely don't cheat on tests
        if: ${{ needs.ConfigureWorkflow.outputs.perform_testing == 'yes' }}
        run: ${{ needs.ConfigureWorkflow.outputs.package_manager }} test

  Analyze:
    name: Analyze (${{ matrix.language }})
    needs: ["Lint", "Test"]
    runs-on: ubuntu-latest
    permissions:
      # required for all workflows
      security-events: write

      # required to fetch internal or private CodeQL packs
      packages: read

      # only required for workflows in private repositories
      actions: read
      contents: read

    strategy:
      fail-fast: false
      matrix:
        include:
          - language: actions
            build-mode: none
          - language: javascript-typescript
            build-mode: none
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v4
        with:
          languages: ${{ matrix.language }}
          build-mode: ${{ matrix.build-mode }}
          # Uncomment to enable stricter security queries:
          # queries: security-extended,security-and-quality

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v4
        with:
          category: "/language:${{matrix.language}}"
